security:

    firewalls:
        # Firewall de la parte de administración o backend
        backend:
            pattern:        ^/backend
            provider:       administradores
            http_basic:     ~
        # Firewall de la extranet a la que se conectan las tiendas
        extranet:
            pattern:        ^/extranet
            provider:       tiendas
            anonymous:      ~
            form_login:
                login_path: /extranet/login
                check_path: /extranet/login_check
            logout:
                path:       /extranet/logout
                target:     /extranet
        # Firewall global utilizado en la parte pública o frontend
        frontend:
            pattern:        ^/*
            provider:       usuarios
            anonymous:      ~
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check
            logout:
                path:       usuario_logout
            remember_me:
                key:        cupon1234
                lifetime:   604800  # 604.800 = 3.600 * 24 * 7 = 1 semana

    access_control:
        - { path: ^/(es|en)/usuario/(login|registro), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en)/usuario/*, roles: ROLE_USUARIO }
        - { path: ^/extranet/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/extranet/*,        roles: ROLE_TIENDA }
        - { path: ^/backend/*,         roles: ROLE_ADMIN }

    encoders:
        Cupon\UsuarioBundle\Entity\Usuario:        { algorithm: sha512, iterations: 10 }
        Cupon\TiendaBundle\Entity\Tienda:          { algorithm: sha512, iterations: 10 }
        Symfony\Component\Security\Core\User\User: sha512

    providers:
        # Usuarios del frontend
        usuarios:
            entity: { class: Cupon\UsuarioBundle\Entity\Usuario, property: email }
        # Usuarios de la extranet
        tiendas:
            entity: { class: Cupon\TiendaBundle\Entity\Tienda, property: login }
        # Usuarios del backend
        administradores:
            memory:
                users:
                    # user = admin, pass = 1234
                    admin: { password: Eti36Ru/pWG6WfoIPiDFUBxUuyvgMA4L8+LLuGbGyqV9ATuT9brCWPchBqX5vFTF+DgntacecW+sSGD+GZts2A==, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_TIENDA, ROLE_USUARIO, ROLE_ALLOWED_TO_SWITCH]
