parameters:
#    usuario.example.class: Cupon\UsuarioBundle\Example

services:
    login_listener:
        class: Cupon\UsuarioBundle\Listener\LoginListener
        scope: container
        arguments: [@security.context, @router]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }
